services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Alexandre08
      MYSQL_DATABASE: forum

  forum:
    build: .
    depends_on:
      - db
    ports:
      - "9090:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_PASSWORD: Alexandre08
      DB_NAME: forum