services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Youyou3000.  # 👈 Obligatoire
      MYSQL_DATABASE: forum
      MYSQL_USER: root                  # 👈 Ce n’est pas utile si tu veux utiliser root directement
      MYSQL_PASSWORD: Youyou3000.       # 👈 Optionnel ici, car root est déjà défini

  forum:
    build: .
    depends_on:
      - db
    ports:
      - "9090:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_PASSWORD: Youyou3000.
      DB_NAME: forum
